os: linux
dist: bionic
language: bash
script:
  - curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
  - git clone https://github.com/crazyuploader/kernel_xiaomi_whyred.git Whyred
  - cd Whyred && git remote -v && git remote add guyi https://github.com/GuaiYiHu/android_kernel_xiaomi_whyred.git && git fetch guyi mkq-mr1 && git rebase -X theirs guyi/mkq-mr1
