dist: bionic
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pyflakes
script: 
- git clone https://gitHub.com/crazyuploader/Python.git python
- cd python && for f in $(ls *.py); do echo "Checking $f"; echo; pyflakes $f; done
- echo "Done!"
