os: linux
dist: bionic
language: bash
before_install:
  - sudo apt-get update && sudo apt autoremove && sudo apt-get install -y python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install bs4 requests pandas
script: 
  - pip3 --version && python --version
