os: linux
dist: bionic
script:
  - curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
  - wget -nv https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r377782.tar.gz
  - tar -xf clang-r377782.tar.gz
  - ls -lh
  - du -sh
