dist: bionic

language: bash

sudo: required

script: 
- sudo apt update && sudo apt -y upgrade && sudo apt install python 
- git clone https://GitHub.com/crazy uploaded/Python.git python
- pip install --upgrade pip
- pip install pyflakes
- cd python && for f in $(ls *.py); do echo "Checking $f"; echo; pyflakes $f; done
