os: linux
dist: bionic
language: python
python: "3.7"
install: 
  - pip install --upgrade pip setuptools
  - pip install manga-py
script:
  - curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
  - manga-py --reverse-downloading --max-volumes 2 https://manganelo.com/manga/grand_blue --name 'Manga'
  - cd Manga && cd Manga && ls
  - curl -F chat_id="${KERNEL_CHAT_ID}" -F document=@"$(pwd)/vol_058.zip" https://api.telegram.org/bot${BOT_API_TOKEN}/sendDocument
