dist: bionic

language: bash

sudo: required

script: 
- git clone https://gitHub.com/crazyuploader/Python.git python
- sudo pip install pyflakes && clear
- cd python && for f in $(ls *.py); do echo "Checking $f"; echo; pyflakes $f; done
