dist: bionic

language: bash

sudo: required

script: 
- sudo apt update && sudo apt -y upgrade && sudo apt install python 
- git clone https://gitHub.com/crazyuploader/Python.git python
- sudo pip install --upgrade pip
- sudo pip install pyflakes
- cd python && for f in $(ls *.py); do echo "Checking $f"; echo; pyflakes $f; done
