pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -O https://raw.githubusercontent.com/crazyuploader/Docker-Builder/master/speedtest/Dockerfile
    docker build -t crazyuploader/speedtest .
