version: 2
jobs:
  build:
    docker:
      - image: "crazyuploader/minimal_ubuntu:latest"
    steps:
      - checkout
      - run:
          name: Running Script
          command: |
            bash script.sh
