version: 2
jobs:
  build:
    docker:
      - image: "crazyuploader/speedtest:latest"
    steps:
      - checkout
      - run:
          name: Running Script
          command: |
            speedtest
