name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Release
        run: echo ${{ github.ref_name}}
      - name: Script
        run: bash script.sh
